
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.1
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.1",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.SequelizeMetaScalarFieldEnum = {
  name: 'name'
};

exports.Prisma.EventScalarFieldEnum = {
  id: 'id',
  topic: 'topic',
  payload: 'payload',
  payload_hash: 'payload_hash',
  created_at: 'created_at'
};

exports.Prisma.Legacy_skill_mapScalarFieldEnum = {
  legacy_v5_id: 'legacy_v5_id',
  skill_id: 'skill_id'
};

exports.Prisma.Prod_challenge_emsi_skillsScalarFieldEnum = {
  emsi_skill_id: 'emsi_skill_id',
  challenge_id: 'challenge_id'
};

exports.Prisma.Prod_job_emsi_skillsScalarFieldEnum = {
  emsi_skill_id: 'emsi_skill_id',
  job_id: 'job_id'
};

exports.Prisma.Prod_user_emsi_skillsScalarFieldEnum = {
  user_id: 'user_id',
  skill_id: 'skill_id',
  skill_source_ids: 'skill_source_ids',
  std_skill_id: 'std_skill_id',
  emsi_id: 'emsi_id'
};

exports.Prisma.Prod_v5_skillsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  std_skill_id: 'std_skill_id'
};

exports.Prisma.SkillScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  category_id: 'category_id',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at',
  dev_id: 'dev_id'
};

exports.Prisma.Skill_categoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Skill_eventScalarFieldEnum = {
  id: 'id',
  event_id: 'event_id',
  user_id: 'user_id',
  skill_id: 'skill_id',
  skill_event_type_id: 'skill_event_type_id',
  source_id: 'source_id',
  source_type_id: 'source_type_id',
  created_at: 'created_at'
};

exports.Prisma.Skill_event_typeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Skill_replacementScalarFieldEnum = {
  skill_id: 'skill_id',
  replacing_skill_id: 'replacing_skill_id',
  category_id: 'category_id',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Source_typeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Temp_dev_emsi_skillScalarFieldEnum = {
  id: 'id',
  emsi_id: 'emsi_id',
  name: 'name'
};

exports.Prisma.Temp_dev_user_emsi_skillsScalarFieldEnum = {
  user_id: 'user_id',
  skill_id: 'skill_id',
  skill_source_ids: 'skill_source_ids',
  std_skill_id: 'std_skill_id'
};

exports.Prisma.Temp_legacy_v5_skillScalarFieldEnum = {
  id: 'id',
  name: 'name',
  external_id: 'external_id',
  taxonomy_id: 'taxonomy_id',
  taxonomy_name: 'taxonomy_name'
};

exports.Prisma.Temp_prod_distinct_user_emsi_skillsScalarFieldEnum = {
  emsi_id: 'emsi_id',
  skill_id: 'skill_id'
};

exports.Prisma.Temp_prod_emsi_skillScalarFieldEnum = {
  emsi_skill_id: 'emsi_skill_id',
  emsi_id: 'emsi_id',
  name: 'name'
};

exports.Prisma.Temp_prod_taas_job_v5_skillsScalarFieldEnum = {
  v5_skill_id: 'v5_skill_id',
  name: 'name'
};

exports.Prisma.Temp_raw_emsi_skillsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  category_id: 'category_id',
  category_name: 'category_name',
  subcategory_id: 'subcategory_id',
  subcategory_name: 'subcategory_name',
  isSoftware: 'isSoftware',
  type_id: 'type_id',
  type_name: 'type_name'
};

exports.Prisma.Temp_taas_job_skill_mappingScalarFieldEnum = {
  v5_skill_id: 'v5_skill_id',
  name: 'name',
  std_skill_name: 'std_skill_name',
  std_skill_id: 'std_skill_id'
};

exports.Prisma.Temp_taas_job_skillsScalarFieldEnum = {
  v5_skill_id: 'v5_skill_id'
};

exports.Prisma.Temp_taas_role_skill_mappingScalarFieldEnum = {
  id: 'id',
  name: 'name',
  skill_id: 'skill_id'
};

exports.Prisma.User_skillScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  skill_id: 'skill_id',
  user_skill_level_id: 'user_skill_level_id',
  created_at: 'created_at',
  updated_at: 'updated_at',
  user_skill_display_mode_id: 'user_skill_display_mode_id'
};

exports.Prisma.User_skill_display_modeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.User_skill_levelScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Work_skillScalarFieldEnum = {
  id: 'id',
  work_id: 'work_id',
  work_type_id: 'work_type_id',
  skill_id: 'skill_id',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};


exports.Prisma.ModelName = {
  SequelizeMeta: 'SequelizeMeta',
  event: 'event',
  legacy_skill_map: 'legacy_skill_map',
  prod_challenge_emsi_skills: 'prod_challenge_emsi_skills',
  prod_job_emsi_skills: 'prod_job_emsi_skills',
  prod_user_emsi_skills: 'prod_user_emsi_skills',
  prod_v5_skills: 'prod_v5_skills',
  skill: 'skill',
  skill_category: 'skill_category',
  skill_event: 'skill_event',
  skill_event_type: 'skill_event_type',
  skill_replacement: 'skill_replacement',
  source_type: 'source_type',
  temp_dev_emsi_skill: 'temp_dev_emsi_skill',
  temp_dev_user_emsi_skills: 'temp_dev_user_emsi_skills',
  temp_legacy_v5_skill: 'temp_legacy_v5_skill',
  temp_prod_distinct_user_emsi_skills: 'temp_prod_distinct_user_emsi_skills',
  temp_prod_emsi_skill: 'temp_prod_emsi_skill',
  temp_prod_taas_job_v5_skills: 'temp_prod_taas_job_v5_skills',
  temp_raw_emsi_skills: 'temp_raw_emsi_skills',
  temp_taas_job_skill_mapping: 'temp_taas_job_skill_mapping',
  temp_taas_job_skills: 'temp_taas_job_skills',
  temp_taas_role_skill_mapping: 'temp_taas_role_skill_mapping',
  user_skill: 'user_skill',
  user_skill_display_mode: 'user_skill_display_mode',
  user_skill_level: 'user_skill_level',
  work_skill: 'work_skill'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
